conversion cast to fix build
The compile error was also mentioned here: [1]

```
| ../sources/bmcweb-1.0+git/src/ssl_key_handler.cpp:293:61: error: conversion from 'std::chrono::duration<long long int>::rep' {aka 'long long int'} to 'long int' may change value [-Werror=conversion]
|   293 |     X509_gmtime_adj(X509_getm_notAfter(x509), duration.count());
|       |                                               ~~~~~~~~~~~~~~^~
| cc1plus: all warnings being treated as errors
```

The relevant function signature only accepts 'long' anyways, so assuming
that is what the authors intention was.

```
ASN1_TIME *X509_gmtime_adj(ASN1_TIME *s, long adj);
```

Looking at the value of `duration.count()` it is `315569520`
which is representable by a 32-bit signed integer type.

References:
[1] https://gerrit.openbmc.org/c/openbmc/openbmc/+/89780/comments/d1fbedfb_3eca650e

Change-Id: Idecb18acc4c7862d0ca56efd090736cacbdd8164
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>