Fix CI on generated-enum
Generated enum files include `json.hpp' which causes the CI failures
like
```
/var/jenkins-openbmc/workspace/ci-repository/openbmc/bmcweb/redfish-core/include/generated/enums/acceleration_function.hpp:4:1: error: included header json.hpp is not used directly [misc-include-cleaner,-warnings-as-errors]
    4 | #include <nlohmann/json.hpp>
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    5 |
```

So, this will add a `misc-include-cleaner` to bypass the included header
check.

```
// NOLINTNEXTLINE(misc-include-cleaner)
```

Tested:
- Compiles good
- CI passes

Change-Id: Id1d5e981b1de37398aa02c3303357e66fe902efd
Signed-off-by: Myung Bae <myungbae@us.ibm.com>